/*
 * blogc: A blog compiler.
 * Copyright (C) 2015-2016 Rafael G. Martins <rafael@rafaelmartins.eng.br>
 *
 * This program can be distributed under the terms of the BSD License.
 * See the file LICENSE.
 */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif /* HAVE_CONFIG_H */

#include "../common/utils.h"
#include "settings.h"
#include "renderer.h"


static void
render_settings(const char *key, const char *value, bc_string_t *s)
{
    bc_string_append_printf(s, "%s = %s\n", key, value);
}


static void
render_environment(const char *key, const char *value, bc_string_t *s)
{
    bc_string_append_printf(s, "        -D %s=\"%s\" $\n", key, value);
}


char*
blogc_ninja_render(blogc_ninja_settings_t *settings)
{
    bc_string_t *rv = bc_string_new();

    bc_string_append(rv,
        "# This build file was generated by blogc-ninja " PACKAGE_VERSION ".\n"
        "# It should not be edited manually.\n"
        "\n"
        "ninja_required_version = 1.3\n"
        "\n");

    bc_trie_foreach(settings->settings,
        (bc_trie_foreach_func_t) render_settings, rv);

    bc_string_append(rv,
        "\n"
        "blogc_command = $\n");
    if (NULL != bc_trie_lookup(settings->settings, "locale"))
        bc_string_append(rv, "    LC_ALL=\"$locale\" $\n");
    bc_string_append(rv, "    blogc $\n");
    bc_trie_foreach(settings->env, (bc_trie_foreach_func_t) render_environment,
        rv);
    bc_string_append(rv,
        "    $null\n"
        "\n");




    bc_string_append(rv,
        "rule blogc_entry\n"
        "    command = $blogc_command $\n"
        "        -D DATE_FORMAT=\"$date_format\" $\n"
        "        -t $template_dir/$main_template $\n"
        "        -o $out $\n"
        "        $in\n"
        "    description = BLOGC ENTRY $out\n"
        "\n"
        "rule blogc_listing\n"
        "    command = $blogc_command $\n"
        "        -D DATE_FORMAT=\"$date_format\" $\n"
        "        -t $template_dir/$main_template $\n"
        "        -o $out $\n"
        "        $in\n"
        "    description = BLOGC ENTRY $out\n"
        "\n"

        "build $output_dir/about/index.html: blogc_entry $content_dir/about.txt | $template_dir/$main_template\n");

    return bc_string_free(rv, false);
}
